### ISSUE TITLE
time is different with kemenag official prayer times

### ISSUE THREAD

**Issue by fathiraz** [hablullah/go-prayer#3]
hey @RadhiFadlillah thanks a lot for your great effort for this library, may Allah bless you.

i want use this package as source of our application prayer times, but when it compared to [kemenag official prayer times ](https://bimasislam.kemenag.go.id/jadwalshalat) the result was different. here is my code without any corrections config:
```go
// Calculate prayer schedule in Bekasi for 2023.
asiaJakarta, _ := time.LoadLocation("Asia/Jakarta")
bekasiSchedules, _ := prayer.Calculate(prayer.Config{
          Latitude:           -6.241586,
	  Longitude:          106.992416,
          Timezone:           asiaJakarta,
          TwilightConvention: prayer.Kemenag(),
          AsrConvention:      prayer.Shafii,
          PreciseToSeconds:   true,
          Corrections:        prayer.ScheduleCorrections{},
}, 2023)
```

the result was
```bash
========== 2023-11-30 ==========
fajr:  2023-11-30 04:02:46 +0700 WIB
dhuhr:  2023-11-30 11:40:28 +0700 WIB
asr:  2023-11-30 15:05:46 +0700 WIB
maghrib:  2023-11-30 17:54:07 +0700 WIB
isha:  2023-11-30 19:09:23 +0700 WIB
====================================
```

wether in kemenag the result was like this
![Capture-2023-11-30-211443](https://github.com/hablullah/go-prayer/assets/6995203/8c6d6ade-02a9-4ff5-a0dd-cb9f21e1cfac)

the data shows
- fajr = minus 3 minutes
- dhuhr = minus 4 minutes
- asr = minus 3 minutes
- maghrib = minus 3 minutes
- isya = minus 3 minutes

my question is, is this expected and we need to fill the corrections config?

**Comment by RadhiFadlillah** [comment]
Hi @fathiraz, sorry for late reply.

Yes, this is an expected behavior. In some locations the local scholar usually will adjust the schedule forward or backward for a few minutes. In Indonesia, from what I understand:

- All azans are commenced **2 minutes after the calculated time**. This is done for safety, to make sure the azan is not announced prematurely before its actual time begin.
- Special for Zuhr time, the azan is commenced **3 minutes after the calculated time**. The 2 minutes is done following the previous point, while the additional 1 minute is for more safety, since there is a hadith that forbade Muslim to pray exactly at the solar noon.
- For Sunrise (Shuruq), in Kemenag's schedule it's written **4 minutes earlier than the calculated time**. This is done because Shuruq is the time limit for Fajr's prayer. This way, even though currently the time is already at Kemenag's Shuruq time, we actually still have additional 4 minutes time to do Fajr's prayer.

So, here is the code with its correction time:

```go
// Calculate prayer schedule in Jakarta for 2023.
asiaJakarta, _ := time.LoadLocation("Asia/Jakarta")
bekasiSchedules, _ := prayer.Calculate(prayer.Config{
	Latitude:           -6.241586,
	Longitude:          106.992416,
	Timezone:           asiaJakarta,
	TwilightConvention: prayer.Kemenag(),
	AsrConvention:      prayer.Shafii,
	PreciseToSeconds:   true,
	Corrections: prayer.ScheduleCorrections{
		Fajr:    2 * time.Minute,
		Sunrise: -4 * time.Minute,
		Zuhr:    3 * time.Minute,
		Asr:     2 * time.Minute,
		Maghrib: 2 * time.Minute,
		Isha:    2 * time.Minute,
	},
}, 2023)
```

**Comment by fathiraz** [comment]
No prob, thank you for your response!
